### ISSUE TITLE
both non-categorical and non-numeric attribute

### ISSUE THREAD

**Issue by pashadude** [alexice/template-scala-parallel-svd-item-similarity#1]
Thank you for great work!

Have not you thought about adding a non-categorical and non-numerical descriptional field, smth. like description consisting of keywords (the number of keywords will be considerably great so one-hot will not really work, but such field can be transferred into numerical data via tf/idf technique)? Will you update the engine in future?

**Comment by alexice** [comment]
Yes. This is possible too, probably it's worth implementing. Actually it will be one-hot encoding as well for text part and you're right it's good to make tf-idf

**Comment by pashadude** [comment]
thnx!
