### ISSUE TITLE
Batched Mysql Queries

### ISSUE THREAD

**Issue by rawoke083** [alexice/template-scala-parallel-svd-item-similarity#2]
HI
IF i increased the dimensions to 1000  i'm running into mysql-errors (max transaction sized etc)
Anyway we can change this to do batches of 100 or ?

Great template btw ! :)

**Comment by alexice** [comment]
I think it's probably better to address question maybe to prediction.io. Persistence layer is transparent for template. I understand that this may be not very convenient, but bid you try with PostgreSQL or ES + HBase?

**Comment by rawoke083** [comment]
No problem , will post there  :)
