### ISSUE TITLE
Bad json response

### ISSUE THREAD

**Issue by feliu** [alexice/template-scala-parallel-svd-item-similarity#3]
thanks for your great job!

I have a problem with your default example, produces a invalid json.

{u'itemScores': [{u'item': u'673', u'score': 0.8030399486432991}, {u'item': u'2', u'score': 0.7535070281756162}, {u'item': u'258', u'score': 0.7419234600626333}, {u'item': u'410', u'score': 0.7385510948678473}, {u'item': u'631', u'score': 0.7195713171519362}]}

I don't understand why...

**Comment by alexice** [comment]
what python version do you use?

**Comment by feliu** [comment]
Python 2.7.10

**Comment by feliu** [comment]
Probably is a python error.
